cli_app:
  src_dir: data/cli_app/src
  dst_dir: data/cli_app/dst
  results_dir: data/cli_app
  threshold: 0.3
  target_production: 100
  target_defect_rate: 0.01

fastapi_app:
  host: 127.0.0.1
  port: 8001
  src_dir: data/fastapi_app/src
  dst_dir: data/fastapi_app/dst
  results_dir: data/fastapi_app
  threshold: 0.3
  target_production: 100
  target_defect_rate: 0.01